# Generated by Django 3.1.2 on 2021-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_questions_iscontest'),
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='poll.Questions'),
        ),
    ]
