# Generated by Django 3.1.2 on 2021-03-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_contest_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='second',
            field=models.BooleanField(default=False),
        ),
    ]
