# Generated by Django 3.1.2 on 2021-03-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0003_auto_20210314_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
