# Generated by Django 3.1.2 on 2021-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_contest_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='canjoin',
            field=models.BooleanField(default=False),
        ),
    ]
