# Generated by Django 3.1.2 on 2021-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='iscontest',
            field=models.IntegerField(default=0),
        ),
    ]
